## Deskripsi Tugas
Mahasiswa melakukan proses pengolahan data dari dataset mentah yang mengandung
berbagai kesalahan. Mahasiswa harus membersihkan data, menganalisis karakteristiknya,
dan menyajikan visualisasi time series yang informatif.
Dataset dapat di download pada LMS.

## Instruksi Tugas
    1. Identifikasi minimal 7 jenis kesalahan data pada dataset.
    2. Lakukan data cleaning untuk memperbaiki kesalahan tersebut.
    3. Hitung statistik deskriptif untuk kolom Sales, Quantity, dan Profit (mean, median, standar
    deviasi).
    4. Siapkan data time series dengan memastikan kolom tanggal benar dan terurut.
    5. Buat 2 visualisasi time series: line chart dan area chart.
    6. Tuliskan analisis singkat (tren, pola, dan pengaruh cleaning).
    7. Buat 2 insight dan 2 rekomendasi.
## Output yang Dikumpulkan
    • Dataset setelah cleaning
    • File Python atau Link Google Colab yang disertakan ke dalam laporan
    • Laporan berupa PDF dengan format nama file: nim_nama_kelas, yang berisi:
        1. Tabel identifikasi error
        2. Hasil analisis deskriptif
        3. Dua visualisasi time series
    • Laporan dan dataset dijadikan satu dalam bentuk RAR dengan format nama:
    nim_nama_kelas

## Import Libray

In [45]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [46]:
df = pd.read_csv('dataset_p7_superstore.csv')
df.head()

,Order ID,Order Date,Ship Date,Category,Sub-Category,Sales,Quantity,Profit,Region
0,CA-2024-10287,26/07/2023,2023-08-02,Furniture,Furnishings,466.7,3,NaN,West
1,CA-2024-10329,06/11/2023,2023-11-11,Technology,Accessories,99999,-1,45000,East
2,CA-2024-10323,2024-05-29,2024-05-31,Furniture,Chairs,1533.18,6,179.43,Central
3,CA-2024-10145,29/07/2023,2023-08-01,TECHNOLOGY,Phones,1451.94,3,78.94,East
4,CA-2024-10055,2024-12-21,2024-12-25,Technology,Accessories,532.45,2,65.43,West

In [47]:
df.isnull().sum()

Order ID         0
Order Date      13
Ship Date        4
Category         4
Sub-Category     4
Sales           32
Quantity         4
Profit          24
Region           4
dtype: int64

In [48]:
df.duplicated().sum()

np.int64(18)

In [49]:
df['Category'].unique()

array(['Furniture', 'Technology', 'TECHNOLOGY', 'Office Supplies',
       'technology', 'Office Supply', 'FURNITURE', nan, 'OFFICE SUPPLIES',
       'office supplies', 'furniture', 'Office Supplies ', 'Tech',
       'Furniture ', 'Furn', 'Technology '], dtype=object)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 378 entries, 0 to 377
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order ID      378 non-null    object
 1   Order Date    365 non-null    object
 2   Ship Date     374 non-null    object
 3   Category      374 non-null    object
 4   Sub-Category  374 non-null    object
 5   Sales         346 non-null    object
 6   Quantity      374 non-null    object
 7   Profit        354 non-null    object
 8   Region        374 non-null    object
dtypes: object(9)
memory usage: 26.7+ KB

In [51]:
df['Profit'].unique()

array([nan, '45000', '179.43', '78.94', '65.43', '211.07', '327.54 IDR',
       '28.41', '13.68', '159.75', '23.09', '216.07', '62.58', '132.44',
       '16.01', '23.87', '10.61', '15.55', '-0.58', '188.09', '38.32',
       '48.52', '158.18', '14.05', '675.18', '9.16', '150.28', '89.86',
       '66.8', '485.26 IDR', '148.83', '52.25', '413.22', '33.13',
       '14.34', '26.76', '144.25', '21.88', '260.17', '200.71', '54.36',
       '43.94', '102.44', '43.55', '78.09', '38.82', '65.4', '98.92',
       '158.73', '107.38', '20.73 IDR', '31.04', '14.59', '602.55',
       '36.86', '51.86', '7.4', '173.5', '28.15', '-7.37', '86.50 IDR',
       '13.78', '19.82', '37.87', '11.34', '42.49', '201.38',
       '216.09 IDR', '80.83', '$155.12', '106.49', '5.16', '95.71',
       '$87.99', '140.83', '64.08', '193.25', '346.2', '-16.14', '55.83',
       '22.24', '-2000', '30.93', '122.36', '59.4', '23.94', '30.72',
       '220.66', '23.54', '420.71', '49.18', '33.4', '97.55', '92.81',
       '-6.91', '43.59', '18.34', '47.27', '304.77', '$138.17', '80.69',
       '19.34', '60.77', '24.28', '136.72', '20.71', '136.88', '57.71',
       '31.0', '51.53', '103.11', '15.08', '30.89', '57.03', '171.95',
       '14.92', '-14.1', '32.52', '101.42', '380.28', '7.69', '167.97',
       '10.59', '27.27', '79.35', '43.44', '23.46', '173.9', '$36.51',
       '310.59', '20.45 IDR', '273.52', '55.69', '$74.55', '144.38',
       '40.31', '19.52', '515.44', '44.58', '13.3', '65.33', '560.45',
       '67.96', '94.73', '42.09', '10.62', '8.86', '18.22', '-5.67',
       '15.83', '685.71', '65.31', '16.24', '52.87 IDR', '446.58',
       '-191.42', '800.1', '82.07', '73.65', '176.22', '$106.32', '33.58',
       '110.47', '137.21', '119.02', '36.48', '40.02', '37.26', '6.69',
       '44.75', '179.88', '104.55', '80.43', '101.07', '80.15', '107.92',
       '28.5', '189.09', '36.83', '51.47', '33.8', '32.06', '59.23',
       '178.73', '159.71', '22.2', '61.2', '155.93', '26.46', '10.65',
       '30.61', '60.88', '222.1', '204.58', '-1.64', '13.67', '257.81',
       '147.85', '15.82', '67.68', '101.0', '144.8', '84.87', '148.35',
       '-0.66', '86.98', '51.83', '169.96', '5.8', '28.74', '34.4',
       '28.8', '77.68', '315.52', '2.71', '52.31', '32.99', '33.67',
       '312.34', '32.54', '568.51', '11.63', '119.59', '24.67', '20.74',
       '-75000', '28.93', '203.71', '20.5', '130.35', '24.61', '24.59',
       '69.03', '$-8.65', '5.95', '47.13', '59.03', '27.12', '120000',
       '42.18', '39.3', '276.76', '155.43', '19.47', '38.59', '14.16',
       '82.88', '77.19', '442.39', '220.02', '6.44', '106.3', '75.32',
       '107.23', '130.9', '4.75', '16.36', '3.11', '39.48', '-50000',
       '149.18', '97.39', '33.75', '17.85', '98.01', '28.34', '34.14',
       '91.79', '25.66', '212.97', '136.29', '53.46', '79.83', '102.25',
       '13.54', '-25.15', '139.71', '102.67', '78.27', '128.21', '39.26',
       '$32.06', '103.15', '128.36', '87.54', '11.13', '14.7', '15.51',
       '301.66', '127.29', '43.9', '81.35', '24.89', '13.52 IDR', '49.15',
       '17.82', '14.29', '115.24', '59.19', '40.57', '28.43 IDR', '75.28',
       '21.23', '183.38', '142.65', '55.36', '12.12', '59.21', '306.39',
       '26.3', '34.01', '2.08', '8.7', '1.5', '94.6', '$90.45', '52.56',
       '33.65', '198.3', '9.92', '23.88', '54.41', '80.22', '297.67',
       '22.26', '43.24', '38.33', '48.74', '38.09', '77.21', '7.42',
       '80.08', '44.79'], dtype=object)

In [52]:
df['Sales'].unique()

array(['466.7', '99999', '1533.18', '1451.94', '532.45', '1427.02',
       '2089.79', nan, '96.57', '2451.24', '28.61', '2312.43', '485.51',
       '1126.46', '191.51', '79.82', '67.53', '55.82', '1564.98',
       '109.52', '923.06', '929.88', '35.11', '3742.2', '44.39',
       '1107.41', '$760.49', '270.56', '2714.88', '1115.88', '164.65',
       '3914.91', '354.4', '492.05', '89.03', '1208.84', '1650.94',
       '387 USD', '$845.79', '250.54', '343.72', '633.25', '281.45',
       '778.95', '799.93', '476.34', '134.69', '157.17', '781.13',
       '4348.36', '219.9', '212.28', '32.7', '1336.19', '118.85',
       '868.95', '2549.48', '167.02', '80.9', '243.66', '76.52', '1274.9',
       '2153.18', '255.54', '2368.37', '893.17', '1731.48', '787.92',
       '68.24', '632.99', '807.68', '359.62', '1532.15', '549.33',
       '769.96', '2676.42', '657.16', '331.48', '71.9', '0.5', '801.02',
       '610.05', '366.65', '1892.57', '542.07', '1492.07', '$163.99',
       '2990.51', '276.71', '$268.56', '1445.43', '2500000', '363.2',
       '669.57', '395.77', '118.81', '280.94', '2980.94', '1257.95',
       '342.07', '227.06', '840.35', '672.0', '199.75', '1564.33',
       '462.07', '171.99', '275.41', '831.36', '439.1', '153.84', '419.5',
       '872.73', '639.46', '600.5', '173.35', '2131.18', '2913.74',
       '94.77', '1692.15', '97.28', '244.66', '2131.85', '867.37',
       '120.73', '2022.8', '110.33', '2457.86', '121.12', '1548.93',
       '615.3', '1704.86', '$322.90', '289.41', '3060.97', '556.72',
       '50.41', '52.53', '766.11', '240.79', '2981.67', '588.96',
       '967.36', '224.62', '12.0', '40.64', '109 USD', '124.92', '73.84',
       '267.38', '3534.08', '1362.45', '597.35', '109.12', '$454.20',
       '290.18', '990.45', '2736.88', '3260.52', '110.92', '671.9',
       '751.75', '1904.9', '173.65', '631.13', '692.64', '1013.26',
       '916.48', '211.05', '295.48', '268.3', '62.97', '210.08',
       '2432.21', '465.65', '863.96', '528.33', '936.52', '225.28',
       '154.21', '3323.39', '203.6', '850 USD', '184.31', '167.8',
       '251.1', '1859.66', '42.32', '471.21', '965.25', '209.83',
       '145.90', '175.43', '758 USD', '1241.46', '1340.46', '1809.13',
       '726.42', '1746.68', '1001.31', '395.21', '2007.73', '756.93',
       '878.04', '436.63', '657.86', '313.9', '692.63', '304.85',
       '1491.77', '66.53', '488.03', '1282.05', '817.16', '675.72',
       '1366.88', '90.63', '292.58', '348.15', '342.84', '2973.71',
       '209.34', '3398.04', '237.25', '855.25', '754.37', '86.2',
       '1250000', '662.51', '933.66', '267.93', '132.35', '591.69',
       '32.34', '836.77', '242.06', '35.64', '850000', '195.0', '200.8',
       '2511.89', '1031.25', '67.33', '427.14', '376.72', '2017.2',
       '752.54', '2704.3', '2418.48', '500.78', '1174.93', '801.45',
       '2002.88', '88.43', '$39.82', '31.15', '94.21', '249.07', '999999',
       '61 USD', '876.49', '553.77', '330.2', '103.37', '191.09',
       '281.53', '236.89', '541.48', '553.8', '1100.73', '875 USD',
       '223 USD', '1050.1', '559.89', '101.78', '584.06', '738.42',
       '769.92', '1091.56', '243.91', '$134.86', '1841.07', '765 USD',
       '475.11', '2237.87', '79.78', '24.77', '39.25', '97.39', '1735.35',
       '846.63', '277 USD', '774.08', '641.04', '141.15', '386.18',
       '78.85', '674.5', '1256 USD', '471.85', '352.46', '121.29',
       '1420.09', '83.49', '1363.38', '1058.85', '449.52', '90.16',
       '611.5', '2324.61', '342.03', '1070.37', '103.91', '427.02',
       '41.8', '12.00', '1180.75', '469.42', '206.85', '1583.0', '59.02',
       '156.01', '388.81', '1795.7', '2519.48', '1220.38', '1330.98',
       '218.69', '947.8', '182.95', '663.32', '155.11'], dtype=object)

In [53]:
df['Quantity'].unique()

array([' 3 ', '-1', '6', '3', '2', '5', '4', '7', '1', '5 pcs', '3 pcs',
       nan, '0', ' 2 ', ' 6 ', ' 4 ', '4 pcs', ' 7 '], dtype=object)

In [54]:
df.describe()

,Order ID,Order Date,Ship Date,Category,Sub-Category,Sales,Quantity,Profit,Region
count,378,365,374,374,374,346,374,354,374
unique,360,310,299,15,13,331,17,332,4
top,CA-2024-10305,2024-02-13,2024-12-25,Office Supplies,Art,2549.48,2,32.54,West
freq,2,4,4,133,37,2,80,3,108

### Temuan Kesalahan Dataset

Terdapat beberapa kesalahan yang ditemukan dalam dataset, diantaranya:
1. Missing Values
2. Duplikat Data
3. Tipe data kolom tanggal object bukan date (Order Date & Ship Date)
4. Inkonsistensi value fitur Category
5. Inkonsistensi value fitur Quantity (pcs, -)
6. Inkonsistensi value fitur Profit ($, IDR)
7. Inkonsistensi value fitur Sales ($,USD)

Dari beberapa kesalahan di atas, perlu dilakukannya pre prosessing data terlebih dahulu

## DATA CLEANING

In [55]:
# Hapus Duplikat Data
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [56]:
# Hapus Missing Values
df = df.dropna()
df.isnull().sum()

Order ID        0
Order Date      0
Ship Date       0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Profit          0
Region          0
dtype: int64

In [57]:
def parse_date(date_str):
    if pd.isna(date_str):
        return pd.NaT
    
    date_str = str(date_str).strip()
    try:
        return pd.to_datetime(date_str, format='%d/%m/%Y')
    except:
        pass
    try:
        return pd.to_datetime(date_str, format='%Y-%m-%d')
    except:
        pass
    try:
        return pd.to_datetime(date_str, format='%m-%d-%Y')
    except:
        pass
    try:
        return pd.to_datetime(date_str)
    except:
        return pd.NaT
    

df['Order Date'] = df['Order Date'].apply(parse_date)
df['Ship Date'] = df['Ship Date'].apply(parse_date)
df.dtypes

Order ID                object
Order Date      datetime64[ns]
Ship Date       datetime64[ns]
Category                object
Sub-Category            object
Sales                   object
Quantity                object
Profit                  object
Region                  object
dtype: object

In [58]:

df.shape

(305, 9)

In [59]:
df.head()

,Order ID,Order Date,Ship Date,Category,Sub-Category,Sales,Quantity,Profit,Region
1,CA-2024-10329,2023-11-06,2023-11-11,Technology,Accessories,99999,-1,45000,East
2,CA-2024-10323,2024-05-29,2024-05-31,Furniture,Chairs,1533.18,6,179.43,Central
3,CA-2024-10145,2023-07-29,2023-08-01,TECHNOLOGY,Phones,1451.94,3,78.94,East
4,CA-2024-10055,2024-12-21,2024-12-25,Technology,Accessories,532.45,2,65.43,West
5,CA-2024-10093,2023-09-23,2023-09-29,Furniture,Bookcases,1427.02,5,211.07,West

In [60]:
df['Category'] = df['Category'].str.title().str.strip()
df['Sub-Category'] = df['Sub-Category'].str.title().str.strip()
df['Region'] = df['Region'].str.title().str.strip()

In [62]:
df['Category'].unique()

array(['Technology', 'Furniture', 'Office Supplies', 'Office Supply',
       'Tech', 'Furn'], dtype=object)